[package]
name = "abstracted-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
tokio = { version = "1.38.0", features = ["fs", "net"] }
serde = { version = "1.0", optional = true }

[features]
serde = ["dep:serde"]
